name: Build Marlin Firmwares

on:
  push:
    branches: ["main"]

jobs:
  build-firmwares:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Generate-build-list
        run: /bin/sh ./builder.sh
