name: Build Marlin Firmwares

on:
  workflow_call:
    inputs:
      prefix:
        description: tag prefix to use
        required: true
        type: string
        default: ""
      parent:
        description: The top level (relative to configs/) directory to build.
        required: true
        type: string
        default: ""

jobs:
  build-marlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Build all flavors
        run: /bin/sh ./builder.sh ${{ inputs.parent }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - build-marlin
    steps:
      - name: create tag
        id: tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ inputs.prefix }}-${{ steps.date.outputs.tag }}
          tag_exists_error: false
          force_push_tag: true
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ inputs.prefix }}-${{ steps.date.outputs.tag }}
          title: ${{ inputs.prefix }}-${{ steps.date.outputs.tag }}
          files: |
            ${{ inputs.parent }}*.bin
