name: Build Marlin Firmwares

on:
  push:
    branches: ["main"]

jobs:
  Kingroon-kp3s-pro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: kingroon-kp3s-pro
        run: /bin/sh ./builder.sh Kingroon_KP3S_PRO
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          title: Kingroon-KPS3-Pro
          files: |
            Kingroon*.bin
