name: Build Marlin Firmwares

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  Kingroon-kp3s-pro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Build all flavors
        run: /bin/sh ./builder.sh Kingroon_KP3S_PRO
        env:
          REPO_TAG: ${{ steps.date.outpus.tag }}
      - name: create tag
        id: tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.date.outputs.tag }}
          tag_exists_error: false
          force_push_tag: true
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.date.outputs.tag }}
          title: Kingroon-KPS3-Pro
          files: |
            Kingroon*.bin
