name: Build Marlin Firmwares

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  Kingroon-kp3s-pro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "tag=$(date +%s)" >> "$GITHUB_OUTPUT"
      - id: kingroon-kp3s-pro
        run: /bin/sh ./builder.sh Kingroon_KP3S_PRO
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.date.outputs.tag }}
          title: Kingroon-KPS3-Pro
          files: |
            Kingroon*.bin
