name: Build Marlin Firmwares

on:
  push:
    branches: ["main"]

jobs:
  build-prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  Kingroon-kp3s-pro:
    runs-on: ubuntu-latest
    needs: build-prep
    steps:
      - id: Firmware builder
        run: /bin/sh ./builder.sh Kingroon_KP3S_PRO
