name: Build Marlin Firmwares

on:
  push:
    branches: ["master"]

jobs:
  build-firmwares:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Generate-build-list
        run: for i in `ls`; do test -d ${i} && echo $i >> build-list; done
      - id: Build-things
        run: cat build-list
