name: Build Marlin Firmwares

on:
  push:
    branches: ["main"]

jobs:
  Kingroon-kp3s-pro:
    runs-on: ubuntu-latest
    needs: build-prep
    steps:
      - uses: actions/checkout@v3
      - id: kingroon-kp3s-pro
        run: /bin/sh ./builder.sh Kingroon_KP3S_PRO
