name: Build Creality firmwares

on:
  push:
    branches:
      - "main"
    paths:
      - configs/Creality/**

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: creality
      parent: Creality
