name: Build Creality firmwares

on:
  push:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality.yaml

jobs:
  get-current-date:
    runs-on: ubuntu-latest
    outputs:
      date_tag: ${{ steps.date_tag.outputs.date_tag }}
    steps:
      - id: date_tag
        run: echo "date_tag=$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"
  # Ender3 with the BTT SKR Mini V2
  Creality-Ender3-SKRMiniV2-bugfix-2_1_x-bltouch:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_env: STM32F103RC_btt_USB
      config_dir: configs/Creality/Ender-3/btt-skr-mini-e3-v2/bugfix-2.1.x/bltouch
      prefix: creality
      artifact_key: firmware-builder
  Creality-Ender3-SKRMiniV2-bugfix-2_1_x-stock:
    needs: Creality-Ender3-SKRMiniV2-bugfix-2_1_x-bltouch
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_env: STM32F103RC_btt_USB
      config_dir: configs/Creality/Ender-3/btt-skr-mini-e3-v2/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  # Ender3 with the v422 version of the OEM board
  Creality-Ender3-oem_v422-bugfix-2_1_x-bltouch:
    needs:
      - get-current-date
      - Creality-Ender3-SKRMiniV2-bugfix-2_1_x-stock
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_env: STM32F103RE_creality
      build_obj: firmware-${{ needs.get-current-date.outputs.date_tag }}.bin
      config_dir: configs/Creality/Ender-3/oem_v422/bugfix-2.1.x/bltouch
      ini_dir: configs/Creality/Ender-3/oem_v422/bugfix-2.1.x/ini
      prefix: creality
      artifact_key: firmware-builder
  Creality-Ender3-oem_v422-bugfix-2_1_x-stock:
    needs:
      - get-current-date
      - Creality-Ender3-oem_v422-bugfix-2_1_x-bltouch
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_env: STM32F103RE_creality
      build_obj: firmware-${{ needs.get-current-date.outputs.date_tag }}.bin
      config_dir: configs/Creality/Ender-3/oem_v422/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  Creality-CR10-oem-bugfix-2_1_x-stock:
    needs:
      - Creality-Ender3-oem_v422-bugfix-2_1_x-stock
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      config_dir: configs/Creality/CR-10_V3/oem/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  Debug-job:
    needs: Creality-CR10-oem-bugfix-2_1_x-stock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      - name: look at files
        run: ls -lhR firmware-builder/
