name: Build Creality firmwares

on:
  push:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality.yaml

jobs:
  Build-Creality-Ender3-Firmwares:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        board:
          - btt-skr-mini-e3-v2
          - oem_v422
        branch:
          - bugfix-2.1.x
        flavor:
          - stock
          - bltouch
        include:
          - environ: STM32F103RC_btt_USB
            board: btt-skr-mini-e3-v2
            object: firmware.bin
          - environ: STM32F103RE_creality
            board: oem_v422
            object: firmware.bin
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: ${{ matrix.board }}-${{ matrix.branch }}-${{ matrix.flavor }}
    with:
      build_env: ${{ matrix.environ }}
      build_obj: ${{ matrix.object }}
      config_dir: configs/Creality/Ender-3/${{ matrix.board }}/${{ matrix.branch }}/${{ matrix.flavor }}
      prefix: creality
      artifact_key: firmware-builder
  Debug-job:
    needs: Creality-Ender3-oem_v422-bugfix-2_1_x-stock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      - name: look at files
        run: ls -lhR firmware-builder/
