name: Build Creality firmwares

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: creality
      parent: Creality_Ender3_BTT-SKR-Mini-E3-v2
