name: Build Creality firmwares

on:
  push:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality.yaml

jobs:
  Ender-3:
    strategy:
      matrix:
        board:
          - oem_v422
          - btt-skr-mini-e3-v2
        branch:
          - bugfix-2.0.x
          - bugfix-2.1.x
        flavor:
          - bltouch
          - stock
    uses: fuzzy/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: ${{ matrix.board }}-${{ matrix.branch }}-${{ matrix.flavor }}
    with:
      build_env: STM32F103RC_btt_USB
      build_obj: Marlin/.pio/build/STM32F103RC_btt_USB/firmware.bin
      config_dir: configs/Creality/Ender-3/${{ matrix.board }}/${{ matrix.branch }}/${{ matrix.flavor }}
  # build:
  #   strategy:
  #     matrix:
  #       parent:
  #         - Creality
  #       model:
  #         - CR-10_V3
  #         - CR-30_PrintMill
  #         - Ender-2
  #         - Ender-3
  #   uses: ./.github/workflows/build.yaml
  #   name: ${{ matrix.parent }}-${{ matrix.model }}
  #   with:
  #     prefix: creality
  #     parent: ${{ matrix.parent }}
  #     model: ${{ matrix.model }}
