name: Build Creality firmwares

on:
  push:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality.yaml

jobs:
  Creality-Ender3-SKRMiniV3-bugfix-2_1_x-bltouch:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: btt-skr-mini-e3-v2-bugfix-2.1.x-bltouch
    with:
      build_env: STM32F103RC_btt_USB
      config_dir: configs/Creality/Ender-3/btt-skr-mini-e3-v2/bugfix-2.1.x/bltouch
      prefix: creality
      artifact_key: firmware-builder
  Creality-Ender3-SKRMiniV3-bugfix-2_1_x-stock:
    needs: btt-skr-mini-e3-v2-bugfix-2.1.x-bltouch
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: btt-skr-mini-e3-v2-bugfix-2.1.x-stock
    with:
      build_env: STM32F103RC_btt_USB
      config_dir: configs/Creality/Ender-3/btt-skr-mini-e3-v2/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  Creality-Ender3-oem_v422-bugfix-2_1_x-bltouch:
    needs: btt-skr-mini-e3-v2-bugfix-2.1.x-stock
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: oem_v422-bugfix-2.1.x-bltouch
    with:
      config_dir: configs/Creality/Ender-3/oem_v422/bugfix-2.1.x/bltouch
      prefix: creality
      artifact_key: firmware-builder
  Creality-Ender3-oem_v422-bugfix-2_1_x-stock:
    needs: oem_v422-bugfix-2.1.x-bltouch
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: oem_v422-bugfix-2.1.x-stock
    with:
      config_dir: configs/Creality/Ender-3/oem_v422/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  Debug-job:
    needs: oem_v422-bugfix-2.1.x-stock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      - name: look at files
        run: ls -lhR firmware-builder/
