name: CR30 Firmwares

on:
  - workflow_call

jobs:
  get-current-date:
    runs-on: ubuntu-latest
    outputs:
      date_tag: ${{ steps.date_tag.outputs.date_tag }}
    steps:
      - id: date_tag
        run: echo "date_tag=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
  # CR-30 builds
  Creality-CR30-oem-bugfix-2_1_x-stock:
    needs: get-current-date
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_obj: firmware-${{ needs.get-current-date.outputs.date_tag }}.bin
      build_env: STM32F103RE_creality
      flavor: stock
      output_obj: Creality_CR30_OEM_bugfix-2.1.x_stock.bin
      config_dir: configs/Creality/CR-30_PrintMill/oem/bugfix-2.1.x/stock
      ini_dir: configs/Creality/CR-30_PrintMill/oem/bugfix-2.1.x/stock/ini
      prefix: creality
      artifact_key: firmware-builder-${{ github.ref_name }}
