name: Build Creality firmwares

on:
  pull_request:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**

jobs:
  build:
    strategy:
      matrix:
        parent:
          - Creality
        model:
          - CR-10_V3
          - CR-30_PrintMill
          - Ender-2
          - Ender-3
    uses: ./.github/workflows/build.yaml
    with:
      prefix: creality
      parent: ${{ matrix.parent }}
      model: ${{ matrix.model }}
