name: Build Creality firmwares

on:
  push:
    tags:
      - v*
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality*yaml

jobs:
  build-ender2-firmwares:
    uses: ./.github/workflows/creality-ender2.yaml
  build-ender3-firmwares:
    uses: ./.github/workflows/creality-ender3.yaml
  build-cr30-firmwares:
    uses: ./.github/workflows/creality-cr30.yaml
  build-cr10-firmwares:
    uses: ./.github/workflows/creality-cr10.yaml
  Debug-job:
    needs:
      - build-cr10-firmwares
      - build-cr30-firmwares
      - build-ender2-firmwares
      - build-ender3-firmwares
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      # and releases on tag events (which aren't triggered yet)
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Weekly
          files: |
            firmware-builder/*
