name: Build Creality firmwares

on:
  # Do weekly builds
  schedule:
    - cron: "0 0 * * 0"
  # TODO: check the event type to not publish artifacts
  #       if we're running because of a pull request

  # Build on pushes to the main branch (PR has been merged)
  push:
    branches:
      - "main"
    paths:
      - builder.sh
      - configs/Creality/**
      - .github/workflows/creality.yaml

jobs:
  build-ender3-firmwares:
    uses: ./.github/workflows/creality-ender3.yaml
  # CR-10 builds
  Creality-CR10-oem-bugfix-2_1_x-stock:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      build_obj: firmware.hex
      output_obj: Creality_CR-10_V3_OEM_bugfix-2.1.x_stock.bin
      config_dir: configs/Creality/CR-10_V3/oem/bugfix-2.1.x/stock
      prefix: creality
      artifact_key: firmware-builder
  Debug-job:
    needs:
      - build-ender3-firmwares
      - Creality-CR10-oem-bugfix-2_1_x-stock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      # Handle scheduled weekly releases
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.event.schedule == '0 0 * * 0' && startsWith(github.ref, 'refs/tags/') == false }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: weekly
          prerelease: false
          title: Release
          files: |
            firmware-builder/*
      # and releases on tag events (which aren't triggered yet)
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.schedule != '0 0 * * 0' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Weekly
          files: |
            firmware-builder/*
