name: Build Geeetech Firmwares

on:
  push:
    branches:
      - main
    paths:
      - builder.sh
      - configs/Geeetech/**

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: geeetech
      parent: Geeetech
