name: Build Geeetech Firmwares

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - configs/Geeetech/**
      - .github/workflows/geeetech*yaml

jobs:
  build-a10-firmwares:
    uses: ./.github/workflows/geeetech-a10.yaml
  build-a20-firmwares:
    uses: ./.github/workflows/geeetech-a20.yaml
  build-a30-firmwares:
    uses: ./.github/workflows/geeetech-a30.yaml
  Debug-job:
    needs:
      - build-a10-firmwares
      - build-a20-firmwares
      - build-a30-firmwares
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder
          path: firmware-builder
      - name: Show artifacts
        run: ls -lh firmware-builder/
      # release weekly builds
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.event_name == 'schedule' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Geeetech Firmwares Weekly ${{ github.ref_name }}
          files: |
            firmware-builder/*
      # release on tag events
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: release
          prerelease: false
          title: Geeetech Firmwares ${{ github.ref_name }}
          files: |
            firmware-builder/*
