name: Build A30* Firmwares

on:
  - workflow_call

jobs:
  Geeetech-A30-bugfix-2_1_x-stock:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      flavor: stock
      prefix: geeetech
      artifact_key: firmware-builder-${{ github.ref_name }}
      build_obj: firmware.bin
      build_env: STM32F103VE
      config_dir: configs/Geeetech/A30/oem/bugfix-2.1.x/stock
      output_obj: Geeetech_A30_OEM_bugfix-2.1.x_stock.hex
  Geeetech-A30M-bugfix-2_1_x-stock:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      flavor: stock
      prefix: geeetech
      artifact_key: firmware-builder-${{ github.ref_name }}
      build_obj: firmware.bin
      build_env: STM32F103VE
      config_dir: configs/Geeetech/A30M/oem/bugfix-2.1.x/stock
      output_obj: Geeetech_A30M_OEM_bugfix-2.1.x_stock.hex
  Geeetech-A30T-bugfix-2_1_x-stock:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      flavor: stock
      prefix: geeetech
      artifact_key: firmware-builder-${{ github.ref_name }}
      build_obj: firmware.bin
      build_env: STM32F103VE
      config_dir: configs/Geeetech/A30T/oem/bugfix-2.1.x/stock
      output_obj: Geeetech_A30T_OEM_bugfix-2.1.x_stock.hex
