name: Build Geeetech Weeklies

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: geeetech-weekly
      parent: Geeetech
      dryrun: false
