name: Build Geeetech Firmwares

on:
  pull_request:
    branches:
      - main
    paths:
      - builder.sh
      - configs/Geeetech/**

jobs:
  build:
    strategy:
      matrix:
        parent:
          - Geeetech
        model:
          - A10
          - A10M
          - A10T
          - A20
          - A20M
          - A20T
          - A30
          - A30M
          - A30T
    uses: ./.github/workflows/build.yaml
    with:
      prefix: geeetech
      parent: ${{ matrix.parent }}
      model: ${{ matrix.model }}
