name: Build Kingroon Firmwares

on:
  push:
    branches:
      - main
    paths:
      - builder.sh
      - configs/Kingroon/**

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: kingroon
      parent: Kingroon
