name: Build Kingroon Firmwares

on:
  pull_request:
    branches:
      - main
    paths:
      - builder.sh
      - configs/Kingroon/**

jobs:
  Kingroon-KP3S_PRO-oem-bugfix_2_1_x-bltouch:
    needs: Creality-Ender3-SKRMiniV3-bugfix-2_1_x
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    name: oem-bugfix-2.1.x-bltouch
    with:
      build_env: mks_robin_nano_v1v2
      build_obj: Robin_nano35.bin
      config_dir: configs/Kingroon/KP3S-PRO/oem/bugfix-2.1.x/bltouch
      prefix: kingroon
      artifact_key: firmware-builder
  build:
    strategy:
      matrix:
        parent:
          - Kingroon
        model:
          - KP3S-PRO
    uses: ./.github/workflows/build.yaml
    name: ${{ matrix.parent }}-${{ matrix.model }}
    with:
      prefix: kingroon
      parent: ${{ matrix.parent }}
      model: ${{ matrix.model }}
