name: Build Kingroon Firmwares

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      prefix: kingroon
      parent: Kingroon_KP3S_PRO
