name: Build Kingroon Firmwares

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - configs/Kingroon/**
      - .github/workflows/kingroon*yaml

jobs:
  build-kp3s-firmwares:
    uses: ./.github/workflows/kingroon-kp3s.yaml
  Debug-job:
    needs:
      - build-kp3s-firmwares
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: firmware-builder-${{ github.ref_name }}
          path: firmware-builder
      - name: Show artifacts
        run: ls -lh firmware-builder/
      # release weekly builds
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.event_name == 'schedule' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: kingroon-weekly
          prerelease: true
          title: Kingroon Firmwares Weekly ${{ github.ref_name }}
          files: |
            firmware-builder/*
      # release on tag events
      - uses: marvinpinto/action-automatic-releases@latest
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: kingroon
          prerelease: false
          title: Kingroon Firmwares ${{ github.ref_name }}
          files: |
            firmware-builder/*
