name: KP3S* Firmwares

on:
  - workflow_call

jobs:
  Kingroon-KP3S_PRO-oem-bugfix_2_1_x-bltouch:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      prefix: kingroon
      build_env: mks_robin_nano_v1v2
      build_obj: Robin_nano35.bin
      config_dir: configs/Kingroon/KP3S-PRO/oem/bugfix-2.1.x/bltouch
      output_obj: Kingroon_KP3S-PRO_OEM_bugfix-2.1.x_bltouch.bin
      artifact_key: firmware-builder-${{ github.ref_name }}
  Kingroon-KP3S_PRO-oem-bugfix_2_1_x-stock:
    uses: thePrintFarm/printer-firmware-actions/.github/workflows/marlin.yaml@main
    with:
      prefix: kingroon
      build_env: mks_robin_nano_v1v2
      build_obj: Robin_nano35.bin
      config_dir: configs/Kingroon/KP3S-PRO/oem/bugfix-2.1.x/stock
      output_obj: Kingroon_KP3S-PRO_OEM_bugfix-2.1.x_stock.bin
      artifact_key: firmware-builder-${{ github.ref_name }}
