name: Build Kingroon Firmwares

on:
  pull_request:
    branches:
      - main
    paths:
      - builder.sh
      - configs/Kingroon/**

jobs:
  build:
    strategy:
      matrix:
        parent:
          - Kingroon
        model:
          - KP3S-PRO
    uses: ./.github/workflows/build.yaml
    name: ${{ matrix.parent }}-${{ matrix.model }}
    with:
      prefix: kingroon
      parent: ${{ matrix.parent }}
      model: ${{ matrix.model }}
