name: Build Weekly Snapshots

jobs:
  build:
    strategy:
      matrix:
        vendor:
          - Creality
          - Geeetech
          - Kingroon
    uses: ./.github/workflows/build.yaml
    with:
      prefix: ${{ matrix.vendor }}-weekly
      parent: ${{ matrix.vendor }}
      dryrun: false
      cleanup: true
